export { 
  isOfAge, 
  isBoolean, 
  isNotEmpty,
  isNumbersOnly,
  isOverDaysOld,
  isValidAlphaNum,
  isValidDate,
  isValidEmail,
  isValidImage,
  isValidName,
  isValidPhone,
  isValidString,
  isValidUserName,
  onlyOneTruthy,
  sanitizeData,
  stripHTML,
} from "./validators"